# ------Pod-------

apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    app: webserver
spec:
  containers:
    - image: nginx:latest
      name: nginxcontainer



# -----Service----

apiVersion: v1
kind: Service
metadata:
  name: myfirstpod-service
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP