apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "40Mi"
        cpu: "40m"
      limits:
        memory: "80Mi"
        cpu: "200m"