#####  cat mysql_rs1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql_1
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
		  
##  [root@k8s-master tmp]# cat mysql_rs2.yaml

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlrs
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [mysql_1, mysql_2]}
  template:
    metadata:
      name: mysql
      labels:
        app: mysql_2
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root



# -----------------------<Another Example>---------------------
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: nginx_1
spec:
  containers:
    - image: nginx:latest
      name: nginx


# replicaset.yaml

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nginx_1, nginx_2]}
  template:
    metadata:
      name: nginx
      labels:
        app: nginx_2
    spec:
      containers:
        - image: nginx:latest
          name: nginx