apiVersion: v1
kind: Pod
metadata:
 name: toleration-pod
spec:
 containers:
 - name: nginx
   image: nginx
 tolerations:
 - key: "app"         # label of taints
   operator: "Equal"
   value: "webserver"
   effect: "NoSchedule"